### ISSUE TITLE
`waitForElement` step transform incorrectly

### ISSUE THREAD

**Issue by jecfish** [webdriverio/recorder-extension#5]
Steps:

1. Import this JSON file in Recorder. https://github.com/puppeteer/replay/issues/268
2. Export it as WebDriverIO script.
3. Observe the step below is transform to 
    ```
    // json
    {
      "type": "waitForElement", 
      "selectors": ["div.pay-container li"], 
      "operator": "==", 
      "count": 2
     }
     
     // wdio
     await expect(browser.$("div.pay-container li")).toBeElementsArrayOfSize(2)
     ```
4. Run it with chrome driver. Test is failed. [NOT OK]
6.  Modify the script to `browser.$$`. Script rerun successfully.

Expect the step transform correctly to `$$`.

**Comment by christian-bromann** [comment]
fixed and published as `v0.3.3`
