### ISSUE TITLE
Do we need to add step to scroll to off-viewport element before the action?

### ISSUE THREAD

**Issue by jecfish** [webdriverio/recorder-extension#6]
Steps:

1. Import this JSON file in Recorder. https://github.com/puppeteer/replay/issues/268
2. Export it as WebDriverIO script.
3. Run it with chrome driver.
4. The script failed at the step: click Americano. [NOT OK]
    `Element is not clickable at point x y. Other element would receive the click: ...`
6. Repeat step 2 and 3.
7. Manually scroll down to Americano.
8. The "click Americano" step run successfully.

Notes:

Follow the side note in the https://webdriver.io/docs/api/element/click. 
I am not sure if this is something can be addressed by the auto-generated script or should I manually remove the fixed header menu.

**Comment by christian-bromann** [comment]
The WebDriver spec defines that interacting with elements requires to scroll the element into viewport. However that sometimes is not reliable when e.g. there are position fixed elements overlaying the element. I will investigate this.

**Comment by christian-bromann** [comment]
I tweaked and improved the selectors a bit and this doesn't seem to be a problem anymore.
